@startuml join_chanel


scale 3
skinparam ActorFontName B Nazanin
skinparam ParticipantFontName B Nazanin
skinparam DefaultFontName B Nazanin
skinparam SequenceGroupHeaderFontName Arial
skinparam DefaultTextAlignment left

 
actor "کاربر:" as user

user -> user : خروج از سامانه()


@enduml