@startuml search_chanel_fragment


scale 3
skinparam DefaultFontName Vazir
skinparam DefaultTextAlignment center

 
participant "کانال:" as chanel
participant "کانال‌ها" as chanels
participant "کانال: کانال در حال بررسی" as current_chanel

note right of chanels
    کانال‌ها مجموعه‌ای از
    کانال‌های موجود است
end note

[-> chanel : پیدا کردن کانال(اطلاعات کانال)
activate chanel

loop به ازای هر کانال در حال بررسی در کانال‌ها
    chanel -> current_chanel : اطلاعات کانال در حال بررسی = گرفتن اطلاعات کانال()
    break اطلاعات کانال در حال بررسی = اطلاعات کانال
        [<-- chanel : کانال در حال بررسی
    end
end

[<-- chanel : هیچ‌مقدار
deactivate chanel


@enduml