@startuml signup


scale 3
skinparam DefaultFontName Vazir
skinparam DefaultTextAlignment left

 
actor "کاربر بالقوه:" as potential_user
participant "ایمیل:" as email
participant "تلفن:" as phone
participant "کاربر:" as user

potential_user -> potential_user : ثبت‌نام()
loop
    potential_user -> potential_user: وارد کردن شناسه ()
    alt ورودی منطبق با الگوی ایمیل است و تکراری نیست
        break
            potential_user -> email ** : «create»
        end
    else ورودی منطبق با الگوی تلفن است و تکراری نیست
        break
            potential_user -> phone ** : «create»
        end
    end
end
potential_user -> potential_user : وارد کردن رمز عبور()
potential_user -> user ** : «create»


@enduml