@startuml leave_chanel

scale 2
left to right direction
skinparam DefaultFontName B Nazanin

package "زیرسیستم مشاهده محتوا" {
    object "__عضو کانال:__" as member
    object "__کانال:__" as chanel

    member --> chanel
}

@enduml