@startuml see_content

scale 2
left to right direction
skinparam DefaultFontName B Nazanin


package "زیرسیستم مشاهده محتوا" {
    object "__عضو کانال:__" as member
    object "__کانال:__" as chanel
    object "__محتوا:__" as content

    member --> chanel
    chanel --> content
}

@enduml