@startuml buy_subscription

scale 3
skinparam DefaultFontName B Nazanin
skinparam ArrowMessageAlignment right

class "Subscription" as subscription {
    Subscription()
}

class "Chanel" as chanel {
    getSubscription()
    getFee(subscriptionType)
}

class "Member" as member {
    addSubscription(newSubscription)
}

class "User" as user {
    getCredit()
    decreaseCredit(subscriptionFee)
}

class "ContentFacade" {
    seeSubscription(member)
}

class "AccountFacade" {
    getCredit(member)
    decreaseCredit(member, subscriptionFee)
}

class "MonetaryFacade" {
    buySubscription(member, subscriptionType)
}

class "DatabaseFacade" {
    save(newSubscription)
}

class "SubscriptionFacade" {
    seeSubscription(member)
}

chanel "                    1" o-up- "+" member
subscription "              *" -down- "1" chanel
member "1" *-right- "*" subscription
member "*" -left- "1" user
MonetaryFacade  ..>  AccountFacade :use
SubscriptionFacade  ..>  ContentFacade :use
SubscriptionFacade ..>  MonetaryFacade :use
MonetaryFacade ..>  DatabaseFacade :use
ContentFacade .>  chanel :use
AccountFacade ..>  user :use
MonetaryFacade .>  chanel :use
MonetaryFacade .>  member :use
@enduml
