@startuml choose_manager


scale 3
skinparam DefaultFontName B Nazanin
skinparam ArrowMessageAlignment right


class "Chanel" as chanel {
    setManager(choosenMember)
}

class "Member" as member {
    promote(newManager)
}

class "Manager" as manager {
    Manager()
}

class setManagerFacade {
    setManager(owner, choosenMember)
}

class ChannelFacade {
    setManager(owner, choosenMember)
}


class "DatabaseFacade" {
    save(newManager)
}

chanel "            1" o-- "            +" member
member "        1" -- "          0..1" manager
chanel "1" -- "*" manager
setManagerFacade ..> ChannelFacade :use
ChannelFacade ..> chanel :use
ChannelFacade ..> DatabaseFacade :use

@enduml
