@startuml create_content


scale 3
skinparam DefaultFontName B Nazanin
skinparam ArrowMessageAlignment right


class "Content" as content {
    Content()
}

class "Channel" as chanel {
    createContent(contentInfo)
    publish(newContent)
}

class CreateContentFacade {
    createContent(producer, contentInfo)
}

class ContentFacade {
    createContent(contentInfo)
}

class DatabaseFacade {
    save(newContent)
}

content "           *" -- "             1" chanel
CreateContentFacade ..> ContentFacade :use
ContentFacade ..> chanel :use
ContentFacade ..> DatabaseFacade :use


@enduml
