@startuml create_chanel

scale 3
skinparam DefaultFontName B Nazanin
skinparam ArrowMessageAlignment right

class "کاربر" as user {
    درخواست ایجاد کانال(اطلاعات کانال)
    افزودن عضویت(عضو کانال)
}

class "کانال" as chanel {
    گرفتن نام کانال()
}

class "عضو کانال" as member {
    ارتقا به تولیدکننده(تولیدکننده محتوا)
}

class "صاحب کانال" as owner {
}

user "          1" -- "*" chanel
chanel "        1" o-- "            +" member
member "1" -- "0..1" owner
user "1" -- "*" member

@enduml
