@startuml choose_manager


scale 4
skinparam DefaultFontName Vazir
skinparam ArrowMessageAlignment right
skinparam classAttributeIconSize 0


class "Chanel" as chanel {
    +void setManager(Member choosenMember)
}

class "Member" as member {
    +void promote(Manager newManager)
}

class "Manager" as manager {
    Manager()
}

class setManagerFacade {
    +void setManager(Owner owner, Member choosenMember)
}

class ChannelFacade {
    +void setManager(Owner owner, Member choosenMember)
}


class "DatabaseFacade" {
    +void save(Manager newManager)
}

chanel "            1" o-- "            +" member
member "        1" -- "          0..1" manager
chanel "1" -- "*" manager
setManagerFacade ..> ChannelFacade :use
ChannelFacade ..> chanel :use
ChannelFacade ..> DatabaseFacade :use


@enduml