@startuml create_content


scale 4
skinparam DefaultFontName Vazir
skinparam ArrowMessageAlignment right
skinparam classAttributeIconSize 0


class "Content" as content {
    Content()
}

class "Channel" as chanel {
    +void createContent(string contentInfo)
    -void publish(Content newContent)
}

class CreateContentFacade {
    +void createContent(Producer producer, string contentInfo)
}

class ContentFacade {
    +void createContent(string contentInfo)
}

class DatabaseFacade {
    +void save(Content newContent)
}

content "           *" -- "             1" chanel
CreateContentFacade ..> ContentFacade :use
ContentFacade ..> chanel :use
ContentFacade ..> DatabaseFacade :use


@enduml