@startuml deposit_profit


scale 3
skinparam DefaultFontName B Nazanin
skinparam ArrowMessageAlignment right

abstract "تولیدکننده محتوا" as producer {
    درصد سود
    واریز سود(مقدار سود)
}

class "Channel" as chanel {
    totalProfit
    deposit()
    calculateProfit()
    report()

}

class "User" as user {
    deposit(share * totalProfit)
}

class "Member" as member {
    getShare()
}

class MonetaryFacade {
    deposit()
}

class ChannelFacade {
    deposit()
    deposit(currentMember, share * totalProfit)
}

class ChannelsCatalog {
    getAllChannels()
}

class AccountFacade {
    deposit(currentMember, share * totalProfit)
}

chanel "1" -- "             +" member
member "1" -- "         0..1" producer
chanel "        *" -- "+" user
member "                    *" -- "1" user
ChannelsCatalog "1" -- "*" chanel
MonetaryFacade ..> ChannelFacade :use
ChannelFacade ..> AccountFacade :use
ChannelFacade ..> chanel :use
ChannelFacade ..> ChannelsCatalog :use
AccountFacade ..> user :use

@enduml
