@startuml deposit_profit


scale 4
skinparam DefaultFontName Vazir
skinparam ArrowMessageAlignment right
skinparam classAttributeIconSize 0

class "Channel" as chanel {
    -double totalProfit
    +void deposit()
    -double calculateProfit()
    +void report()

}

class "User" as user {
    +void deposit(double share * totalProfit)
}

class "Member" as member {
    +double getShare()
}

class MonetaryFacade {
    +void deposit()
}

class ChannelFacade {
    +void deposit()
    +void deposit(Member currentMember, double share * totalProfit)
}

class ChannelsCatalog {
    +List<Channel> getAllChannels()
}

class AccountFacade {
    +void deposit(Member currentMember, double share * totalProfit)
}

chanel "1" -- "             +" member
member "1" -- "         0..1" producer
chanel "        *" -- "+" user
member "                    *" -- "1" user
ChannelsCatalog "1" -- "*" chanel
MonetaryFacade ..> ChannelFacade :use
ChannelFacade ..> AccountFacade :use
ChannelFacade ..> chanel :use
ChannelFacade ..> ChannelsCatalog :use
AccountFacade ..> user :use

@enduml
