@startuml join_chanel


scale 3
skinparam DefaultFontName B Nazanin


class "User" as user {
    addMembership(newMember)
}

class "Chanel" as chanel {
    addMember(user)
}

class "Member" as member {
    Member()
}

class EntryFacade {
    joinChannel(user, foundChannel)
}

class JoinChannelFacade {
    searchChannel(channelInfo)
    joinChanel(channelInfo)
}

class ContentFacade {
    searchChannel()
}

class DatabaseFacade {
    save(newMember)
}

chanel "1" o-left- "+" member
user "*" -- "*" chanel
JoinChannelFacade ..> ContentFacade :use
JoinChannelFacade ..> EntryFacade :use
EntryFacade ..> chanel :use
EntryFacade ..> DatabaseFacade :use
EntryFacade ..> user :use



@enduml
