@startuml join_chanel


scale 3
skinparam DefaultFontName B Nazanin
skinparam classAttributeIconSize 0


class "User" as user {
    +void addMembership(Member newMember)
}

class "Chanel" as chanel {
    +Member addMember(User user)
}

class "Member" as member {
    Member()
}

class EntryFacade {
    +void joinChannel(User user, Channel foundChannel)
}

class JoinChannelFacade {
    +Channel searchChannel(string channelInfo)
    +void joinChanel(string channelInfo)
}

class ContentFacade {
    +Channel searchChannel()
}

class DatabaseFacade {
    +void save(Member newMember)
}

chanel "1" o-left- "+" member
user "*" -- "*" chanel
JoinChannelFacade ..> ContentFacade :use
JoinChannelFacade ..> EntryFacade :use
EntryFacade ..> chanel :use
EntryFacade ..> DatabaseFacade :use
EntryFacade ..> user :use



@enduml
