@startuml leave_chanel


scale 4
skinparam DefaultFontName Vazir
skinparam classAttributeIconSize 0

class "Chanel" as chanel {
    +void removeMember(Member member)
}

class "member" as member {
    +void leave()
}

class "User" as user {
    +void removeMembership(Member member)
}

class LeaveChanelFacade {
    +void leaveChanel(Member member)
}

class ContentFacade {
    +void leaveChanel(Member member)
}

class AccountFacade {
    +void removeMembership(Member member)
}

class DatabaseFacade {
    +void delete(Member member)
}

member "1" -- "*" user
chanel "    1" o-- "    +" member
ContentFacade ..> AccountFacade :use
ContentFacade ..> member :use
LeaveChanelFacade ..> ContentFacade :use
AccountFacade ..> user :use
AccountFacade ..> DatabaseFacade :use


@enduml