@startuml login

scale 3
skinparam DefaultFontName B Nazanin


class LoginFacade {
    requestLogin()
    login(username, password)
}

class EntryFacade {
    login(username, password)
}

class DatabaseFacade {
    getUser(username)
}

LoginFacade ..> EntryFacade :use
EntryFacade ..> DatabaseFacade :use

@enduml
