@startuml login


scale 4
skinparam DefaultFontName Vazir
skinparam classAttributeIconSize 0

class LoginFacade {
    +void requestLogin()
    +void login(string username, string password)
}

class EntryFacade {
    +void login(string username, string password)
}

class DatabaseFacade {
    +User getUser(string username)
}

LoginFacade ..> EntryFacade :use
EntryFacade ..> DatabaseFacade :use


@enduml