@startuml logout


scale 4
skinparam DefaultFontName Vazir
skinparam classAttributeIconSize 0


class LogoutFacade {
    +void requestLogout()
}

class EntryFacade {
    +void logout(User user)
}

LogoutFacade ..> EntryFacade :use


@enduml