@startuml logout

scale 3
skinparam DefaultFontName B Nazanin
skinparam classAttributeIconSize 0

class LogoutFacade {
    +void requestLogout()
}

class EntryFacade {
    +void logout(User user)
}

LogoutFacade ..> EntryFacade :use

@enduml
