@startuml promote_content


scale 3
skinparam DefaultFontName B Nazanin
skinparam ArrowMessageAlignment right


class "Chanel" as chanel {
    getContents()
    promoteContent(contentInfo)
}

class Content {
    info
    getInfo()
    promote()
}

class PromoteContentFacade {
    getContents(producer)
    promoteContents(producer, contentsInfo)
}

class ViewContentFacade {
    getContents(producer)
}

class ProduceContentFacade {
    promoteContents(producer, contentsInfo)
}

class ContentsCatalog {
    getChannelsContent()
}



Content "           *" -- "1" chanel
producer "+" -- "                   1" chanel
PromoteContentFacade ..> ViewContentFacade :use
PromoteContentFacade ..> ProduceContentFacade :use
ViewContentFacade ..> chanel :use
ProduceContentFacade ..> chanel :use
@enduml
