@startuml promote_content


scale 4
skinparam DefaultFontName Vazir
skinparam ArrowMessageAlignment right
skinparam classAttributeIconSize 0

class "Chanel" as chanel {
    +List<Content> getContents()
    +void promoteContent(string contentInfo)
}

class Content {
    -string info
    +string getInfo()
    +void promote()
}

class PromoteContentFacade {
    +List<Content> getContents(Producer producer)
    +void promoteContents(Producer producer, string contentsInfo)
}

class ViewContentFacade {
    +List<Contents> getContents(Producer producer)
}

class ProduceContentFacade {
    +void promoteContents(Producer producer, string contentsInfo)
}

class ContentsCatalog {
    +List<Contents> getChannelsContent()
}



Content "           *" -- "1" chanel
producer "+" -- "                   1" chanel
PromoteContentFacade ..> ViewContentFacade :use
PromoteContentFacade ..> ProduceContentFacade :use
ViewContentFacade ..> chanel :use
ProduceContentFacade ..> chanel :use


@enduml