@startuml search_chanel

scale 3
skinparam DefaultFontName B Nazanin

class "Chanel" as chanel {
    getInfo()
}

class SearchFacade {
    searchChanel(chanelInfo)
}

class ContentFacade {
    searchChanel(chanelInfo)
}

class ChannelsCatalog {
    getAllChannels()
}

ChannelsCatalog "1" -- "*" chanel
ContentFacade ..> ChannelsCatalog :use
ContentFacade ..> chanel :use
SearchFacade ..> ContentFacade :use
@enduml
