@startuml searchChanel

scale 4
skinparam DefaultFontName Vazir
skinparam classAttributeIconSize 0

class "Chanel" as chanel {
    +string getInfo()
}

class SearchFacade {
    +Channel searchChanel(string chanelInfo)
}

class ContentFacade {
    +Channel searchChanel(string chanelInfo)
}

class ChannelsCatalog {
    +List<Channel> getAllChannels()
}

ChannelsCatalog "1" -- "*" chanel
ContentFacade ..> ChannelsCatalog :use
ContentFacade ..> chanel :use
SearchFacade ..> ContentFacade :use


@enduml