@startuml see_content

scale 2
skinparam DefaultFontName B Nazanin


class "Content" as content {
    getInfo()
    getAccessLevel()
    getSummary()
}

class "Chanel" as chanel {
    getContents()
    selectContent(contentInfo)
}

class "Member" as member {
    getAccessLevel()
}

class UIContentFacade {
    getContents(member)
    selectContent(member, contentInfo)
}

class ViewContentFacade {
    getContents(member)
    selectContent(member, contentInfo)
}

class ContentsCatalog {
    getChannelContents()
}

content "*" --o "1" chanel
chanel "1" o-left- "+" member
subscription "*" --* "1" member
chanel "1" -- "1" ContentsCatalog
UIContentFacade ..> ViewContentFacade :use
ViewContentFacade ..> chanel :use


@enduml
