@startuml see_content

scale 2
skinparam DefaultFontName B Nazanin
skinparam classAttributeIconSize 0


class "Content" as content {
    -string info
    +string getInfo()
    +string getAccessLevel()
    +strimg getSummary()
}

class "Chanel" as chanel {
    +List<Content> getContents()
    +Content selectContent(string contentInfo)
}

class "Member" as member {
    +string getAccessLevel()
}

class UIContentFacade {
    +List<Content> getContents(Member member)
    +Content selectContent(Member member, string contentInfo)
}

class ViewContentFacade {
    +List<Content> getContents(Member member)
    +Content selectContent(Member member, string contentInfo)
}

class ContentsCatalog {
    +List<Content> getChannelContents()
}

content "*" --o "1" chanel
chanel "1" o-left- "+" member
subscription "*" --* "1" member
chanel "1" -- "1" ContentsCatalog
UIContentFacade ..> ViewContentFacade :use
ViewContentFacade ..> chanel :use


@enduml
