@startuml set_manager_profit


scale 3
skinparam DefaultFontName B Nazanin
skinparam ArrowMessageAlignment right

class "صاحب کانال" as owner {
}

class "Channel" as chanel {
    setManagerProfit(member, profit)
}

class "Member" as member {
    setProfit(profit)
}

class "Manager" as manager {
    profit
    setProfit()
}

class SetManagerFacade {
    setManagerProfit(owner, member, profit)
}

class ChannelFacade {
    setManagerProfit(owner, member, profit)
}

owner "1" -- "1" chanel
chanel "1" o-- "+" member
member "1" -- "0..1" manager
SetManagerFacade ..> ChannelFacade :use
ChannelFacade ..> chanel :use

@enduml
