@startuml set_manager_profit


scale 4
skinparam DefaultFontName Vazir
skinparam ArrowMessageAlignment right
skinparam classAttributeIconSize 0


class "Channel" as chanel {
    +void setManagerProfit(Member member, double profit)
}

class "Member" as member {
    +void setProfit(double profit)
}

class "Manager" as manager {
    -double profit
    +void setProfit(double profit)
}

class SetManagerFacade {
    +void setManagerProfit(Owner owner, Member member, double profit)
}

class ChannelFacade {
    +void setManagerProfit(Owner owner, Member member, double profit)
}

owner "1" -- "1" chanel
chanel "1" o-- "+" member
member "1" -- "0..1" manager
SetManagerFacade ..> ChannelFacade :use
ChannelFacade ..> chanel :use


@enduml