@startuml set_subscription_price


scale 4
skinparam DefaultFontName Vazir
skinparam ArrowMessageAlignment right
skinparam classAttributeIconSize 0

class "Channel" as chanel {
    +void setPrice(double owner)
    +void setSubscriptionPrice(string type, double price)
}

class SetPriceFacade {
    +void setPrice(Owner owner)
    +void setSubscriptionPrice(string type, double price)
}

class ChannelFacade {
    +void setPrice(Owner owner)
    +void setSubscriptionPrice(string type, double price)
}

ChannelFacade ..> chanel :use
SetPriceFacade ..> ChannelFacade :use


@enduml