@startuml set_subscription_price


scale 3
skinparam DefaultFontName B Nazanin
skinparam ArrowMessageAlignment right

class "Channel" as chanel {
    setPrice(owner)
    setSubscriptionPrice(type, price)
}

class SetPriceFacade {
    setPrice(owner)
    setSubscriptionPrice(type, price)
}

class ChannelFacade {
    setPrice(owner)
    setSubscriptionPrice(type, price)
}

ChannelFacade ..> chanel :use
SetPriceFacade ..> ChannelFacade :use


@enduml
