@startuml signup


scale 4
skinparam DefaultFontName Vazir
skinparam classAttributeIconSize 0


class Email {
    Email()
    -string emailAddress
}

class Phone {
    -string phoneNumber
    Phone()
}

class User{
    -string username
    -string password
    User()
}

class SignupFacade {
    +void requestSignup()
    +void signup(string username, string password)
}

class EntryFacade {
    +void signup(string username, string password)
}

class DatabaseFacade {
    +boolean exists(string username)
    +void save(string email)
    +void save(string phone)
    +void save(User user)
}

potential_user "1" -left- "1" Email
potential_user "1" -right- "1" Phone
potential_user "1" -down- "1" User
EntryFacade ..> DatabaseFacade :use
EntryFacade ..> Email :use
EntryFacade ..> Phone :use
EntryFacade ..> User :use
SignupFacade ..> EntryFacade :use


@enduml