@startuml signup

scale 3
skinparam DefaultFontName B Nazanin


class "کاربر بالقوه" as potential_user {
    ثبت‌نام()
    وارد کردن شناسه()
}

class Email {
    Email()
    emailAddress
}

class Phone {
    phoneNumber
    Phone()
}

class User{
    username
    password
    User()
}

class SignupFacade {
    requestSignup()
    signup(username, password)
}

class EntryFacade {
    signup(username, password)
}

class DatabaseFacade {
    exists(username)
    save(email)
    save(phone)
    save(user)
}

potential_user "1" -left- "1" Email
potential_user "1" -right- "1" Phone
potential_user "1" -down- "1" User
EntryFacade ..> DatabaseFacade :use
EntryFacade ..> Email :use
EntryFacade ..> Phone :use
EntryFacade ..> User :use
SignupFacade ..> EntryFacade :use

@enduml
