@startuml update_subscription_time

scale 3
skinparam DefaultFontName B Nazanin
skinparam ArrowMessageAlignment right

class User {
    updateSubscriptions()
}

class Member {
    dailyDecrease()
}

class Subscription {
    remainingTime()
    decreaseTime()
    }

class MonetaryFacade {
    updateSubscriptions()
}

class AccountFacade {
    updateSubscriptions()
}

class DatabaseFacade {
    delete(oldestSubscription)
}


member "1" *-- "*" subscription
user "1" -- "*" member
AccountFacade ..> User :use
AccountFacade ..> DatabaseFacade :use
MonetaryFacade ..> AccountFacade :use

@enduml
