@startuml update_subscription_time


scale 4
skinparam DefaultFontName Vazir
skinparam ArrowMessageAlignment right
skinparam classAttributeIconSize 0

class User {
    +void updateSubscriptions()
}

class Member {
    +void dailyDecrease()
}

class Subscription {
    -int remainingTime
    +void decreaseTime()
    }

class MonetaryFacade {
    +void updateSubscriptions()
}

class AccountFacade {
    +void updateSubscriptions()
}

class DatabaseFacade {
    +void delete(Subscription oldestSubscription)
}


member "1" *-- "*" subscription
user "1" -- "*" member
AccountFacade ..> User :use
AccountFacade ..> DatabaseFacade :use
MonetaryFacade ..> AccountFacade :use


@enduml