@startuml set_manager_profit

scale 2
left to right direction
skinparam DefaultFontName B Nazanin

package "زیرسیستم تولید محتوا" {
    object "__صاحب کانال:__" as owner
    object "__مدیر کانال:__" as manager
    object "__کانال:__" as chanel

    owner --> chanel
    chanel --> manager
}

@enduml