@startuml set_subscription_price

scale 2
left to right direction
skinparam DefaultFontName B Nazanin

package "زیرسیستم تولید محتوا" {
    object "__صاحب کانال:__" as owner
    object "__کانال:__" as chanel

    owner --> chanel
}

@enduml