@startuml set_manager_profit

scale 2
left to right direction
skinparam DefaultFontName B Nazanin

package "زیرسیستم تولید محتوا" {
    object "__صاحب کانال:__" as owner
    object "__کانال:__" as chanel
    object "__اشتراک:__" as subscription

    owner --> chanel
    chanel --> subscription
}

@enduml