@startuml join_chanel

scale 3
skinparam DefaultFontName B Nazanin


class "کاربر" as user {
    عضویت‌های کاربر
}

class "کانال" as chanel {
    (کاربر)اضافه کردن عضو
}

class "عضو کانال" as member {
}

user "*" -- "*" chanel
chanel "1" o-left- "+" member

@enduml
