@startuml promote_content


scale 3
skinparam DefaultFontName B Nazanin
skinparam ArrowMessageAlignment right

abstract "تولیدکننده محتوا" as producer {
}

class "محتوا" as content {
    مشخصات محتوا
    گرفتن مشخصات()
    ارتقای سطح دسترسی()
}

class "کانال" as chanel {
    مشاهده محتویات()
    انتخاب محتوا(مشخصات محتوا)
}

content "           *" -- "1" chanel
producer "+" -- "                   1" chanel


@enduml
