@startuml set_manager_profit


scale 3
skinparam DefaultFontName B Nazanin
skinparam ArrowMessageAlignment right

class "صاحب کانال" as owner {
}

class "کانال" as chanel {
    تعیین سود مدیر(عضو کانال، مقدار سود)
}

class "عضو کانال" as member {
    تعیین سود(مقدار سود)
}

class "مدیر" as manager {
    مقدار سود
    تعیین سود(مقدار سود)
}

owner "1" -- "1" chanel
chanel "1" o-- "+" member
member "1" -- "0..1" manager


@enduml
