@startuml set_subscription_price

scale 2
skinparam DefaultFontName B Nazanin
skinparam ArrowMessageAlignment right

class "صاحب کانال" as owner {
}

class "کانال" as chanel {
    قیمت اشتراک‌ها
    ()تعیین اشتراک
}

owner -- chanel

@enduml
