@startuml user_subsystem

scale 2
left to right direction
skinparam defaultFontName B Nazanin

rectangle "زیرسیستم کاربری"{
    usecase "ثبت‌نام در سامانه" as signup
    usecase "ورود به سامانه" as login
    usecase "خروج از سامانه" as logout
}

actor "کاربر بالقوه" as defactoUser
actor "کاربر" as user

defactoUser -- signup
user -- login
user -- logout

@enduml