@startuml buy_subscription


scale 3
skinparam DefaultFontName Vazir
skinparam DefaultTextAlignment center


actor ":عضو کانال" as member
box "«subsystem»\nGUI" #LightBlue
participant ":SubscriptionFacade" as ui
end box
box "«subsystem»\nزیرسیستم مشاهده محتوا" #LightPink
participant ":ContentFacade" as contentFacade
end box
participant "member\n:Member" as memberObj
box "«subsystem»\nزیرسیستم مالی" #Moccasin
participant ":MonetaryFacade" as monetary
end box
participant "memberChanel\n:Chanel" as chanel
participant "newSubscription\n:Subscription" as subscription
participant "memberUser\n:User" as user


activate member
member -> ui: seeSubscription(member)
activate ui
ui -> contentFacade: seeSubscription(member)
activate contentFacade
contentFacade -> chanel: getSubscriptions()
activate chanel
chanel --> contentFacade: subscriptions
deactivate chanel
contentFacade --> ui: subscriptions
deactivate contentFacade
ui --> member: subscriptions

member -> ui: buySubscription\n(member, subscriptionType)
ui -> monetary: buySubcription\n(member, subscriptionType)
activate monetary
monetary -> user: userCredit = getCredit()
activate user
deactivate user

alt اعتبار عضو کانال < قیمت اشتراک
    monetary --> ui: InsufficientCredit
    ui --> member: insufficientCredit
else else
    monetary -> chanel: getFee(subscriptionType)
    activate chanel
    deactivate chanel
    monetary -> user: decreaseCredit(subscriptionFee)
    activate user
    deactivate user
    monetary -> subscription **: «create»
    monetary -> memberObj: addSubscription\n(newSubscription)
    activate memberObj
    deactivate memberObj
    monetary --> ui: Success
    deactivate monetary
    ui --> member: Success
    deactivate ui
end

deactivate member


@enduml