@startuml create_chanel


scale 4
skinparam DefaultFontName Vazir
skinparam DefaultTextAlignment center

 
actor ":کاربر" as user
box "«subsystem»\nGUI" #LightBlue
participant ":CreateChanelFacade" as ui
end box
box "«subsystem»\nزیرسیستم تولید محتوا" #LightPink
participant ":ChanelFacade" as chanelFacade
end box
participant ":ChanelsCatalog" as chanels
participant "currentChanel\n:Chanel" as currentChanel
box "«subsystem»\nزیرسیستم کاربری" #LightGray
participant ":AccountFacade" as accountFacade
end box
participant "user\n:User" as userObj
participant "newChanel\n:Chanel" as newChanel
participant "firstMember\n:Member" as firstMember
participant "owner\n:Owner" as owner
box "«subsystem»\nپایگاه داده" #Moccasin
participant ":DatabaseFacade" as db
end box


activate user
user -> ui: createChanel\n(chanelInfo)
activate ui
ui -> chanelFacade: createChanel\n(chanelInfo)
activate chanelFacade
loop به ازای هر کانال در حال بررسی در کانال‌ها
    chanelFacade -> currentChanel: getName()
    activate currentChanel
    currentChanel --> chanelFacade: currentChanelName
    deactivate currentChanel
    break نام کانال = نام کانال در حال بررسی
        chanelFacade --> ui: DuplicateName
        ui --> user: DuplicateName
    end
else else
    chanelFacade -> newChanel **: «create»
    activate newChanel
    newChanel -> firstMember ** : «create»
    newChanel -> owner ** : «create»
    newChanel -> firstMember : promoteMember\n(owner)
    activate firstMember
    firstMember --> newChanel
    deactivate firstMember
    newChanel --> chanelFacade
    deactivate newChanel

    chanelFacade -> db: save(newChanel)
    activate db
    deactivate db
    chanelFacade -> db: save(firstMember)
    activate db
    deactivate db
    chanelFacade -> db: save(owner)
    activate db
    deactivate db

    chanelFacade -> accountFacade: addMembership(newMember)
    activate accountFacade
    accountFacade -> userObj: addMembership\n(newMember)
    activate userObj
    userObj --> accountFacade
    deactivate userObj
    accountFacade --> chanelFacade
    deactivate accountFacade
    chanelFacade --> ui
    deactivate chanelFacade
    ui --> user
    deactivate ui
end
deactivate user


@enduml