@startuml deposit_profit


scale 4
skinparam DefaultFontName Vazir
skinparam DefaultTextAlignment center


actor "زمان" as time
box "«subsystem»\nزیرسیستم مالی" #LightBlue
participant ":MonetaryFacade" as monetary
end box
box "«subsystem»\nزیرسیستم تولید محتوا" #LightPink
participant ":ChanelFacade" as chanelFacade
end box
participant ":ChanelsCatalog" as chanels
participant "currentChanel\n:Chanel" as currentChanel
participant "currentMember\n:Member" as member
participant "//correspondingProducer//\n//:producer//" as producer
box "«subsystem»\nزیرسیستم کاربری" #Moccasin
participant ":AccountFacade" as accountFacade
end box
participant "correspondingUser\n:User" as user

activate time
time -> monetary: deposit()
activate monetary
monetary -> chanelFacade: deposit()
activate chanelFacade
loop به ازای هر کانال در حال بررسی در کانال‌ها
    chanelFacade -> currentChanel: deposit()
    activate currentChanel
    currentChanel -> currentChanel : totalProfit =\ncalculateProfit()
    activate currentChanel
    deactivate currentChanel
    loop به ازای هر عضو در حال بررسی در اعضای کانال
        opt عضو قابلیت تولید محتوا دارد
            currentChanel -> member: getShare()
            activate member
            member --> currentChanel: share
            deactivate member
            currentChanel -> chanelFacade: deposit\n(currentMember, share * totalProfit)
            deactivate currentChanel

            chanelFacade -> accountFacade: deposit(currentMember, share * totalProfit)
            activate accountFacade
            accountFacade -> user: deposit\n(share * totalProfit)
            activate user
            user --> accountFacade
            deactivate user
            accountFacade --> chanelFacade
            deactivate accountFacade
        end
    end
    chanelFacade -> currentChanel: report()
    activate currentChanel
    currentChanel --> chanelFacade
    deactivate currentChanel
end
chanelFacade --> monetary
deactivate chanelFacade
deactivate monetary
deactivate time


@enduml