@startuml join_chanel


scale 3
skinparam DefaultFontName Vazir
skinparam DefaultTextAlignment center


actor ":کاربر" as user
box "«subsystem»\nGUI" #LightBlue
participant ":JoinChanelFacade" as ui
end box
participant "کانال پیدا شده\n:کانال" as foundChanel
box "«subsystem»\nزیرسیستم مشاهده محتوا" #LightPink
participant ":EntryFacade" as entryFacade
participant ":ContentFacade" as contentFacade
end box
participant ":کانال" as chanel
participant ":ChanelsCatalog" as chanels
participant "currentChanel\n:Chanel" as currentChanel
participant "newMember\n:Member" as member


activate user
user -> ui: searchChanel(chanelInfo)
activate ui
ui -> contentFacade: searchChanel(chanelInfo)

note left chanel
    این پیام به قسمت ارجاعی ارسال می‌شود
end note

ref over chanel, chanels, currentChanel, contentFacade: جستجوی کانال

note left chanel
    این پیام از قسمت ارجاعی ارسال می‌شود
end note

contentFacade --> ui

activate user
user -> foundChanel : افزودن عضو(کاربر فعلی)
deactivate user

activate foundChanel
|||
foundChanel -> member ** : «create»
foundChanel -> user : افزودن عضویت(عضو جدید)
deactivate foundChanel

activate user
deactivate user


@enduml