@startuml join_chanel


scale 4
skinparam DefaultFontName Vazir
skinparam DefaultTextAlignment center


actor ":کاربر" as user
box "«subsystem»\nGUI" #LightBlue
participant ":JoinChanelFacade" as ui
end box
participant "user\n:User" as userObj
participant "foundChanel\n:Chanel" as foundChanel
box "«subsystem»\nزیرسیستم مشاهده محتوا" #LightPink
participant ":EntryFacade" as entryFacade
participant ":ContentFacade" as contentFacade
end box
participant ":ChanelsCatalog" as chanels
participant "currentChanel\n:Chanel" as currentChanel
participant "newMember\n:Member" as member
box "«subsystem»\nپایگاه داده" #Moccasin
participant ":DatabaseFacade" as db
end box


activate user
user -> ui: searchChanel\n(chanelInfo)
activate ui
ui -> contentFacade: searchChanel(chanelInfo)
activate contentFacade

note left contentFacade
    این پیام به قسمت ارجاعی ارسال می‌شود
end note
ref over chanels, currentChanel, contentFacade: جستجوی کانال
note left contentFacade
    این پیام از قسمت ارجاعی ارسال می‌شود
end note

contentFacade --> ui: foundChanel
deactivate contentFacade
ui --> user: foundChanel

user -> ui: joinChanel\n(foundChanel)
ui -> entryFacade: joinChanel(user, foundChanel)
activate entryFacade
entryFacade -> foundChanel: addMember(user)
deactivate entryFacade
activate foundChanel

foundChanel -> member **: «create»
foundChanel --> entryFacade: newMember
deactivate foundChanel
activate entryFacade
entryFacade -> db: save(newMember)
activate db
db --> entryFacade
deactivate db

entryFacade -> userObj: addMembership(newMember)
activate userObj
deactivate userObj

entryFacade --> ui: Success
deactivate entryFacade
ui --> user: Success
deactivate ui
deactivate user


@enduml