@startuml login


scale 4
skinparam DefaultFontName Vazir
skinparam DefaultTextAlignment center

 
actor ":کاربر" as user
box "«subsystem»\nGUI" #LightBlue
participant ":LoginFacade" as ui
end box
box "«subsystem»\nزیرسیستم کاربری" #LightPink
participant ":EntryFacade" as entryFacade
end box
box "«subsystem»\nپایگاه داده" #Moccasin
participant ":DatabaseFacade" as db
end box

activate user
user -> ui: requestLogin()
activate ui

loop
    user -> ui: login(username password)
    ui -> entryFacade: login(username password)
    activate entryFacade
    entryFacade -> db: getUser(username)
    activate db
    db --> entryFacade
    deactivate db

    alt کاربری یافت نشده است
        entryFacade --> ui: userNotFound
        ui --> user: userNotFound
    else رمز عبور منطبق نیست
        entryFacade --> ui: wrongPassword
        ui --> user: wrongPassword
    else
        break
            entryFacade --> ui: Success
            deactivate entryFacade
            ui --> user: Success
            deactivate ui
        end
    end
end

deactivate user


@enduml