@startuml logout


scale 4
skinparam DefaultFontName Vazir
skinparam DefaultTextAlignment center

 
actor ":کاربر" as user
box "«subsystem»\nGUI" #LightBlue
participant ":LogoutFacade" as ui
end box
box "«subsystem»\nزیرسیستم کاربری" #LightPink
participant ":EntryFacade" as entryFacade
end box

activate user
user -> ui: requestLogout()
activate ui
ui -> entryFacade: logout(user)
activate entryFacade
entryFacade --> ui: Success
deactivate entryFacade
ui --> user: Success
deactivate ui
deactivate user


@enduml