@startuml search_chanel_usecase


scale 3
skinparam DefaultFontName Vazir
skinparam DefaultTextAlignment center


actor "کاربر:" as user
box "«subsystem»\nGUI" #LightBlue
participant ":LoginFacade" as ui
end box
box "«subsystem»\nزیرسیستم مشاهده محتوا" #LightPink
participant ":ContentFacade" as contentFacade
end box
participant ":ChanelsCatalog" as chanels
participant "currentChanel\n:Chanel" as currentChanel


activate user
user -> ui: searchChanel(chanelInfo)
deactivate user
activate ui
ui -> contentFacade: searchChanel(chanelInfo)

note left contentFacade
این پیام به قسمت ارجاعی ارسال می‌شود
end note

ref over contentFacade, chanels, currentChanel: جستجوی کانال

note left contentFacade
این پیام از قسمت ارجاعی ارسال می‌شود
end note

contentFacade --> ui
ui --> user
deactivate ui
deactivate user


@enduml