@startuml search_chanel_fragment


scale 4
skinparam DefaultFontName Vazir
skinparam DefaultTextAlignment center

 
box "«subsystem»\nزیرسیستم مشاهده محتوا" #LightPink
participant ":ContentFacade" as contentFacade
end box
participant ":ChanelsCatalog" as chanels
participant "currentChanel\n:Chanel" as currenChanel


contentFacade <-]: searchChanel(chanelInfo)
activate contentFacade

loop به ازای هر کانال در حال بررسی در کانال‌ها
    contentFacade -> currenChanel: currentChanelInfo = getInfo()
    activate currenChanel
    deactivate currenChanel

    break اطلاعات کانال در حال بررسی = اطلاعات کانال
        contentFacade -->]: currentChanel
    end
end

contentFacade -->] : null
deactivate contentFacade


@enduml