@startuml search_chanel_usecase


scale 3
skinparam DefaultFontName Vazir
skinparam DefaultTextAlignment center


actor "کاربر:" as user
participant ":کانال" as chanel
participant "کانال‌ها" as chanels
participant "کانال در حال بررسی:کانال" as current_chanel


activate user
user -> chanel : پیدا کردن کانال(اطلاعات کانال)
deactivate user

note left chanel
این پیام به قسمت ارجاعی ارسال می‌شود
end note

ref over chanel, chanels, current_chanel : جستجوی کانال

note left chanel
این پیام از قسمت ارجاعی ارسال می‌شود
end note

chanel --> user

activate user
deactivate user


@enduml