@startuml see_content


scale 4
skinparam DefaultFontName Vazir
skinparam DefaultTextAlignment center


actor ":عضو کانال" as member
box "«subsystem»\nGUI" #LightBlue
participant ":ContentFacade" as ui
end box
box "«subsystem»\nزیرسیستم مشاهده محتوا" #LightPink
participant ":ContentFacade" as contentFacade
end box
participant "member\n:Member" as memberObj
participant "chanelContents\n:ContentsCatalog" as contents
participant "memberChanel\n:Chanel" as chanel
participant ":Subscription" as subscription
participant "currentContent\n:Content" as currentContent


activate member
member -> ui: getContents(member)
activate ui
ui -> contentFacade: getContents(member)
activate contentFacade
contentFacade -> chanel: getContents()
activate chanel
chanel --> contentFacade: chanelContents
deactivate chanel
contentFacade --> ui: chanelContents
deactivate contentFacade
ui --> member

member -> ui : selectContent\n(member, contentInfo)
ui -> contentFacade: selectContent\n(member, contentInfo)
activate contentFacade
contentFacade -> chanel: selectContent(contentInfo)
activate chanel
loop به ازای هر محتوای در حال بررسی در محتویات
    chanel -> currentContent : currentContentInfo\n = getInfo()
    activate currentContent
    deactivate currentContent
    
    break مشخصات محتوا = مشخصات محتوای در حال بررسی
        chanel -> currentContent: currentContentAccessLevel\n = getAccessLevel()
        activate currentContent
        deactivate currentContent
        
        chanel -> memberObj: memberAccessLevel\n = getAccessLevel()
        activate memberObj
        deactivate memberObj
        
        alt سطح دسترسی عضو کانال < سطح دسترسی محتوای در حال بررسی
            chanel -> currentContent: currentContentSummary\n = getSummary()
            activate currentContent
            deactivate currentContent
            chanel --> contentFacade: currentSummary
            contentFacade --> ui: summary
            ui --> member: summary
        else else
            chanel --> contentFacade: currentContet
            deactivate chanel
            contentFacade --> ui: content
            deactivate contentFacade
            ui --> member: content
            deactivate ui
        end
    end
end

deactivate member


@enduml