@startuml set_manager_profit


scale 4
skinparam DefaultFontName Vazir
skinparam DefaultTextAlignment center


actor ":صاحب کانال" as owner
box "«subsystem»\nGUI" #LightBlue
participant ":setManagerFacade" as ui
end box
box "«subsystem»\nزیرسیستم تولید محتوا" #LightPink
participant ":ChanelFacade" as chanelFacade
end box
participant ":Chanel" as chanel
participant "member\n:Member" as member
participant "manager\n:Manager" as manager

activate owner
owner -> ui: setManagerProfit\n(owner, member, profit)
activate ui
ui -> chanelFacade: setManagerProfit\n(owner, member, profit)
activate chanelFacade
chanelFacade -> chanel: setManagerProfit\n(member, profit)
activate chanel
chanel -> member: setProfit(profit)
activate member
member -> manager: setProfit(profit)
activate manager
manager --> member
deactivate manager
member --> chanel
deactivate member
chanel --> chanelFacade
deactivate chanel
chanelFacade --> ui
deactivate chanelFacade
ui --> owner
deactivate ui
deactivate owner


@enduml