@startuml set_subscription_price


scale 4
skinparam DefaultFontName Vazir
skinparam DefaultTextAlignment center

actor ":صاحب کانال" as owner
box "«subsystem»\nGUI" #LightBlue
participant ":setPriceFacade" as ui
end box
box "«subsystem»\nزیرسیستم تولید محتوا" #LightPink
participant ":ChanelFacade" as chanelFacade
end box
participant "ownerChanel\n:Chanel" as chanel


activate owner
owner -> ui: setPrice(owner)
activate ui
ui -> chanelFacade: setPrice(owner)
activate chanelFacade
chanelFacade -> chanel: setPrice()
activate chanel
loop به ازای هر نوع اشتراک در اشتراک‌های کانال
    owner -> ui: setSubscriptionPrice\n(type, price)
    ui -> chanelFacade: setSubscriptionPrice\n(type, price)
    chanelFacade -> chanel: setSubscriptionPrice\n(type, price)
    activate chanel
    deactivate chanel
    chanel --> chanelFacade
    deactivate chanel
end
chanelFacade --> ui
deactivate chanelFacade
ui --> owner
deactivate ui
deactivate owner


@enduml