@startuml signup


scale 4
skinparam DefaultFontName Vazir
skinparam DefaultTextAlignment center

 
actor ":کاربر بالقوه" as potential_user
box "«subsystem»\nGUI" #LightBlue
participant ":signupFacade" as ui
end box
box "«subsystem»\nزیرسیستم کاربری" #LightPink
participant ":entryFacade" as entry_facade
end box
box "«subsystem»\nپایگاه داده" #Moccasin
participant ":databaseFacade" as db_facade
end box
participant ":email" as email
participant ":phone" as phone
participant ":user" as user

activate potential_user
potential_user -> ui : requestSignup()
activate ui

loop
    potential_user -> ui: signup(username, password)
    ui -> entry_facade: signup(username, password)
    activate entry_facade
    entry_facade -> db_facade: exists(username)
    activate db_facade
    db_facade --> entry_facade
    deactivate db_facade

    alt نام کاربری تکراری است
        entry_facade --> ui: DuplicateUsername
        ui --> potential_user: DuplicateUsername
    else نام کاربری منطبق با الگوی ایمیل است
        break
            entry_facade -> email **: «create»
            entry_facade -> db_facade: save(email)
            activate db_facade
            db_facade --> entry_facade
            deactivate db_facade
        end
    else ورودی منطبق با الگوی تلفن است
        break
            entry_facade -> phone **: «create»
            entry_facade -> db_facade: save(phone)
            activate db_facade
            db_facade --> entry_facade
            deactivate db_facade
        end
    end
end

entry_facade -> user **: «create»
entry_facade -> db_facade: save(user)
activate db_facade
db_facade --> entry_facade
deactivate db_facade
entry_facade --> ui
deactivate entry_facade
ui --> potential_user: Success
deactivate ui
deactivate potential_user


@enduml