@startuml signup


scale 4
skinparam DefaultFontName Vazir
skinparam DefaultTextAlignment center

 
actor ":کاربر بالقوه" as potentialUser
box "«subsystem»\nGUI" #LightBlue
participant ":SignupFacade" as ui
end box
box "«subsystem»\nزیرسیستم کاربری" #LightPink
participant ":EntryFacade" as entryFacade

end box
box "«subsystem»\nپایگاه داده" #Moccasin
participant ":DatabaseFacade" as db
end box
participant ":Email" as email
participant ":Phone" as phone
participant ":User" as user

activate potentialUser
potentialUser -> ui : requestSignup()
activate ui

loop
    potentialUser -> ui: signup(username, password)
    ui -> entryFacade: signup(username, password)
    activate entryFacade
    
    entryFacade -> db: exists(username)
    activate db
    db --> entryFacade
    
    deactivate db

    alt نام کاربری تکراری است
        entryFacade --> ui: DuplicateUsername
        ui --> potentialUser: DuplicateUsername
    else نام کاربری منطبق با الگوی ایمیل است
        break
            entryFacade -> email **: «create»
            entryFacade -> db: save(email)
            activate db
            db --> entryFacade
            
            deactivate db
        end
    else ورودی منطبق با الگوی تلفن است
        break
            entryFacade -> phone **: «create»
            entryFacade -> db: save(phone)
            activate db
            db --> entryFacade
            
            deactivate db
        end
    end
end

entryFacade -> user **: «create»
entryFacade -> db: save(user)
activate db
db --> entryFacade

deactivate db
entryFacade --> ui
deactivate entryFacade

ui --> potentialUser: Success
deactivate ui
deactivate potentialUser


@enduml