@startuml signup


scale 4
skinparam DefaultFontName Vazir
skinparam DefaultTextAlignment center

 
actor ":کاربر بالقوه" as potential_user
box "«subsystem»\nGUI" #LightBlue
participant ":نمای ثبت‌نام" as register_facade
end box
box "«subsystem»\nزیرسیستم کاربری" #LightPink
participant ":نمای دروازه" as gate_facade
end box
box "«subsystem»\nپایگاه داده" #Moccasin
participant ":نمای پایگاه داده" as db_facade
end box
participant ":ایمیل" as email
participant ":تلفن" as phone
participant ":کاربر" as user

activate potential_user
potential_user -> register_facade : requestSignup()
activate register_facade

loop
    potential_user -> register_facade: signup(نام کاربری، رمز)
    register_facade -> gate_facade: signup(نام کاربری، رمز)
    activate gate_facade
    gate_facade -> db_facade: exists(نام کاربری)
    activate db_facade
    db_facade --> gate_facade
    deactivate db_facade

    alt نام کاربری تکراری است
        gate_facade --> register_facade: خطای نام کاربری تکراری
        register_facade --> potential_user: خطای نام کاربری تکراری
    else نام کاربری منطبق با الگوی ایمیل است
        break
            gate_facade -> email **: «create»
            gate_facade -> db_facade: save(ایمیل)
            activate db_facade
            db_facade --> gate_facade
            deactivate db_facade
        end
    else ورودی منطبق با الگوی تلفن است
        break
            gate_facade -> phone **: «create»
            gate_facade -> db_facade: save(تلفن)
            activate db_facade
            db_facade --> gate_facade
            deactivate db_facade
        end
    end
end

gate_facade -> user **: «create»
gate_facade -> db_facade: save(کاربر)
activate db_facade
db_facade --> gate_facade
deactivate db_facade
gate_facade --> register_facade
deactivate gate_facade
register_facade --> potential_user: پبام موفقیت
deactivate register_facade
deactivate potential_user


@enduml