@startuml update_subscription_time


scale 4
skinparam DefaultFontName Vazir
skinparam DefaultTextAlignment center


actor "زمان" as time
box "«subsystem»\nزیرسیستم مالی" #LightBlue
participant ":MonetaryFacade" as monetary
end box
box "«subsystem»\nزیرسیستم کاربری" #LightPink
participant ":AccountFacade" as accountFacade
end box
participant "currentUser\n:User" as currentUser
participant "currentMember\n:Member" as currentMember
participant "oldestSubscription\n:Subscription" as subscription
box "«subsystem»\nپایگاه داده" #Moccasin
participant ":DatabaseFacade" as db
end box


activate time
time -> monetary: updateSubscriptions()
activate monetary
loop به ازای هر کاربر در حال بررسی در کاربران
    monetary -> accountFacade: updateSubscriptions()
    activate accountFacade
    accountFacade -> currentUser: updateSubscriptions()
    activate currentUser
    loop به ازای هر عضو کانال در عضویت‌ها
        currentUser -> currentMember: dailyDecrease()
        activate currentMember
        currentMember -> subscription: decreaseTime()
        activate subscription
        subscription --> currentMember
        deactivate subscription
        currentMember --> currentUser
        deactivate currentMember
        currentUser --> accountFacade
        deactivate currentUser
        opt زمان باقیمانده قدیمی‌ترین اشتراک = 0
            accountFacade -> db: delete(oldestSubscription)
            activate db
            deactivate db
        end
    end
    accountFacade --> monetary
    deactivate accountFacade
end
deactivate monetary
deactivate time


@enduml