@startuml component


scale 3
skinparam DefaultFontName Vazir
skinparam DefaultTextAlignment center


component "مولفه سیستم" as modelComp {
    component "زیرسیستم کاربری" <<subsystem>> as userComp
    component "زیرسیستم تولید محتوا" <<subsystem>> as produceComp
    component "زیرسیستم مشاهده محتوا" <<subsystem>> as viewComp
    component "زیرسیستم مالی" <<subsystem>> as financialComp

    interface " " as viewFinanInt
    interface " " as viewProdInt
    interface " " as viewUserInt
    interface " " as userProdInt
    interface " " as userfinanInt

    portin " " as p1
    portout " " as p2
}

component "رابط کاربری" <<subsystem>> as ui
component "پایگاه داده" <<subsystem>> as db

note right of ui


                UI


end note

note right of modelComp
Business
logic
end note

note right of db


                Data


end note


userComp - financialComp

financialComp ...> viewFinanInt : use
viewFinanInt - viewComp
produceComp ..> viewProdInt : use
viewProdInt - viewComp
viewComp ..> viewUserInt : use
viewUserInt - userComp
produceComp .> userProdInt : use
userProdInt - userComp
financialComp ..> userfinanInt : use
userfinanInt - userComp

produceComp -- p1
userComp -- p1
viewComp -- p1

ui ..> p1 : use

p2 -- db

userComp ..> p2
produceComp ..> p2
viewComp ..> p2

' userComp -- produceComp
' userComp -- viewComp
' produceComp - viewComp

@enduml