@startuml leave_chanel


scale 4
skinparam DefaultFontName Vazir
skinparam DefaultTextAlignment center


actor ":عضو کانال" as member
participant ":عضو کانال" as memberObj
participant ":کانال" as chanel

activate member
member -> memberObj: خروج()
activate memberObj
memberObj -> chanel: حذف عضو(عضو کانال)
deactivate memberObj
activate chanel
chanel -> member: حذف عضویت(عضو کانال)
activate member
deactivate member
chanel -> memberObj !!: «destory»
deactivate member
deactivate chanel


@enduml