@startuml update_subscription_time


scale 3
skinparam DefaultFontName Vazir
skinparam DefaultTextAlignment center


actor "زمان" as time
participant "کاربران" as users
participant "کاربر در حال بررسی:کاربر" as current_user
participant "عضویت‌ها" as memberships
participant ":عضو کانال" as current_member
participant "قدیمی‌ترین اشتراک:اشتراک" as subscription


note right users
کاربران مجموعه همه کاربرهای سیستم است
end note

note right users
عضویت‌ها مجموعه همه عضویت‌های کاربر در حال بررسی است
end note

activate time
loop به ازای هر کاربر در حال بررسی در کاربران
    time -> current_user : به‌روزرسانی اشتراک‌ها()
    activate current_user
    loop به ازای هر عضو کانال در عضویت‌ها
        current_user -> current_member : کاهش روزانه()
        activate current_member
        current_member -> subscription : کاهش زمان باقیمانده()
        activate subscription
        deactivate subscription
        opt زمان باقیمانده قدیمی‌ترین اشتراک = 0
            current_member -> subscription !! : «destory»
            |||
        end
        deactivate current_member
        |||
    end
    |||
    deactivate current_user
    |||
end
|||
deactivate time


@enduml