@startuml content_subsystem
scale 2
left to right direction
skinparam defaultFontName B Nazanin

rectangle "زیرسیستم محتوا"{
    usecase "عضو شدن در کانال" as join
    usecase "مشاهده محتوا" as see
    usecase "ایجاد کانال" as start
    usecase "تولید محتوا" as create
    usecase "تعیین محتوای ویژه" as specialize
    usecase "تعریف حق عضویت" as fee
    usecase "تعیین مدیر کانال" as raise
    usecase "تعیین سود مدیر کانال" as salary
    usecase "خروج از کانال" as delete
}

actor "کاربر" as user
actor "عضو کانال" as member
actor "//تولیدکننده محتوا//" as producer
actor "مدیر کانال" as admin
actor "صاحب کانال" as owner

admin --|> producer
owner -|> producer

user -- join
member --- see
member --- delete
user -- start
producer -- create
producer -- specialize
owner -- fee
owner -- raise
owner -- salary

@enduml