@startuml content_subsystem
left to right direction

rectangle "زیرسیستم محتوا"{
    usecase "عضو شدن در کانال" as join
    usecase "مشاهده محتوا" as see
    usecase "ایجاد کانال" as start
    usecase "تولید محتوا" as create
    usecase "تعیین محتوای ویژه" as specialize
    usecase "تعریف حق عضویت" as fee
    usecase "تعیین مدیر کانال" as raise
    usecase "تعیین سود مدیر کانال" as salary
    usecase "واریز سود کانال" as pay
}

actor "کاربر" as user
actor "عضو کانال" as member
actor "مدیر کانال" as admin
actor "صاحب کانال" as owner
actor "زمان" as time

user -- join
member -- see
user -- start
admin -- create
owner -- create
admin -- specialize
owner -- specialize
owner -- fee
owner -- raise
owner -- salary
time -- pay


@enduml