@startuml content_subsystem
scale 2
left to right direction
skinparam ActorFontName B Nazanin
skinparam UsecaseFontName B Nazanin
skinparam TitleFontName B Nazanin

rectangle "زیرسیستم محتوا"{
    usecase "تعریف حق عضویت" as fee
    usecase "مشاهده محتوا" as see
    usecase "تعیین مدیر کانال" as raise
    usecase "خروج از کانال" as delete
    usecase "تعیین سود مدیر کانال" as salary
    usecase "جستجوی کانال" as search
    usecase "تولید محتوا" as createC
    usecase "ایجاد کانال" as start
    usecase "تعیین محتوای ویژه" as specialize
    usecase "عضو شدن در کانال" as join
}


actor "کاربر" as user
actor "عضو کانال" as member
actor "//تولیدکننده محتوا//" as producer
actor "مدیر کانال" as admin
actor "صاحب کانال" as owner

admin --|> producer
owner -|> producer

owner -- fee
see -- member
fee -[hidden]- see
owner -- raise
delete -- member
raise -[hidden]- delete
owner -- salary
search -- user
salary -[hidden]- search
producer -- createC
start -- user
createC -[hidden]- start
producer -- specialize
join -- user

join .> search : <<include>>

@enduml